### ISSUE TITLE
Broken languages with custom helpers

### ISSUE THREAD

**Issue by btx** [Nightapes/HumanizeDuration.ts#3]
Hey,

thank you for porting this. I've just noticed that some languages (those with custom helpers) do not work. I tried to fix it. See https://github.com/Nightapes/HumanizeDuration.ts/pull/2

**Comment by Nightapes** [comment]
Hey, 

thank you for the fix!

**Comment by btx** [comment]
Hey, no problemo :)

**Comment by Nightapes** [comment]
So the new Version is: 1.0.1
https://github.com/Nightapes/HumanizeDuration.ts/releases/tag/v1.0.1
