### ISSUE TITLE
Linking to this project from HumanizeDuration.js?

### ISSUE THREAD

**Issue by EvanHahn** [Nightapes/HumanizeDuration.ts#4]
[HumanizeDuration's readme](https://github.com/EvanHahn/HumanizeDuration.js/blob/master/README.md) has a section called "Related modules". Do you mind if I link to your module from there?

**Comment by Nightapes** [comment]
Hey, 
thanks for the offer.  Of course, you can add this module in your readme.
And thanks for the awesome lib.

**Comment by EvanHahn** [comment]
[Done!](https://github.com/EvanHahn/HumanizeDuration.js/commit/157c212d651e229d229cf0445aff3f89e5a095f8)
